### ISSUE TITLE
Project Browser overwriting text

### ISSUE THREAD

**Issue by mwieder** [livecode/livecode-ide#1022]
For sufficiently long object names, the object type is being overwritten by the object name in the Project Browser and there's no way to expand the text field to overcome this. Expanding the width of the PB just correctly adjusts the pinning of the blue script lines icons, but doesn't affect the text positioning.
![projectbrowsertextoverlap](https://cloud.githubusercontent.com/assets/1829071/13826630/b782adde-eb75-11e5-8f6a-0905fec995fa.png)

**Comment by peter-b** [comment]
@mwieder We're only using GitHub issues on an experimental basis for IDE bugs found in LiveCode 8.

Could you please [open a bug report on Bugzilla](http://quality.livecode.com/enter_bug.cgi) for this issue? Thanks.

**Comment by mwieder** [comment]
OK - I'll do that, but I'm a bit confused then... this _is_ for LC8, is the Project Browser not considered part of the IDE?

**Comment by peter-b** [comment]
@mwieder That's a screenshot of the LiveCode 7 project browser... the LiveCode 8 one has been completely rewritten.

**Comment by mwieder** [comment]
!!! ok - my bad. I thought I had been using LC8 for that last week.

**Comment by mwieder** [comment]
I just updated the bug report to reflect the proper LC version.
