### ISSUE TITLE
Default repeatCount of imported gif

### ISSUE THREAD

**Issue by runrevneil** [livecode/livecode-ide#1026]
The default repeatCount for an imported gif is set to "0" in LC8. In previous versions of LC this is initially set to "-1"

**Comment by runrevelanor** [comment]
In 8 images are imported by creating an empty image and then setting the text of it, this means that an image gets the default value for its repeatCount property, however this should be -1 of animated gifs and 0 for other images.

In 7 and earlier images are imported using the import paint from file command, which seems to automatically set the repeatCount.

I haven't updated revIDEImportControl as I am not sure what is more correct.

**Comment by livecodeali** [comment]
We should probably change it back to using the `import paint from file` command - I'm not sure why it was changed in the first place.

**Comment by runrevelanor** [comment]
Will do.
