### ISSUE TITLE
For documentation, update Bootstrap framework to 3.3.7

### ISSUE THREAD

**Issue by macMikey** [livecode/livecode-ide#1397]
(I hope I'm in the right place for this)
For me, updating the following two files fixed the "Make guide outlines in the Dictionary expand/collapse with repeated clicks" issue discussed in This Week In Livecode:
Contents->Tools->Documentation->html_viewer->bootstrap.min.css
and
Contents->Tools->Documentation->html_viewer->css->bootstrap.min.css
to v. 3.3.7.

The current version of Bootstrap is at https://github.com/twbs/bootstrap/releases/download/v3.3.7/bootstrap-3.3.7-dist.zip

Before you start scratching your head, the .min file has all the whitespace, etc. removed, so it is smaller, and, in theory, faster.

**Comment by peter-b** [comment]
@macMikey Okay, so you originally filed [bug 18184](http://quality.livecode.com/show_bug.cgi?id=18184) about the expand/collapse problem.

I've created [bug 18487](http://quality.livecode.com/show_bug.cgi?id=18487) to track the Bootstrap update, and marked it as blocking the expand/collapse fix.
