### ISSUE TITLE
Reduce whitespace in Dictionary

### ISSUE THREAD

**Issue by macMikey** [livecode/livecode-ide#1398]
The documentation is rendered in a browser widget, using the Bootstrap framework (getbootstrap.com).  Bootstrap controls whitespace by separating the screen into 12 equal columns, and moving and resizing the "containers" (bootstrap's jargon for controls that are vertically proportioned).  Unfortunately, like any framework, it isn't perfect because every browser is different.  After fiddling with trying to make this work just using bootstrap, IMHO, the best way to fix this is to re-engineer the dictionary. I would get rid of the monolithic dictionary browser widget, and replace it with several smaller panes, whose dimensions are controlled by the GM.  The panes would be (names pulled from the api.html.template file)
lcdoc_library_chooser (the popup)
lcdoc_list (the panel below on the left)
table_list (top right panel)
lcdoc_body (bottom right)

**Comment by peter-b** [comment]
@macMikey This is being tracked as [bug 18278](http://quality.livecode.com/show_bug.cgi?id=18278) in Bugzilla (which you filed!) I've copied your comment over there.

I'm really sorry, I'm not trying to give you the run-around on this but it does just make things much easier when everything relating to a particular task is kept in one place.
