### ISSUE TITLE
Inconsistent ordering of tools in the project browser footer

### ISSUE THREAD

**Issue by peter-b** [livecode/livecode-ide#580]
The ordering of the controls in the project browser footer is inconsistent.  For example, in this screenshot, the "Align left" tool is not grouped with the other alignment tools.

![screen shot 2015-10-23 at 10 18 36](https://cloud.githubusercontent.com/assets/47528/10688885/72b5be6c-796f-11e5-9ac0-d7820e30f112.png)

**Comment by runrevelanor** [comment]
This seems to be related to the paletteActions widget rather than the Project Browser stack, it doesn't seem to lay out the action buttons in the order they are added.

**Comment by livecodeali** [comment]
Closed by https://github.com/livecode/livecode/pull/3247
