### ISSUE TITLE
In narrow project browser, footer tools are missing with no hint

### ISSUE THREAD

**Issue by peter-b** [livecode/livecode-ide#581]
When the project browser is too narrow for all the footer tools to be shown, there is no hint that some tools are missing from the footer.

This screenshot illustrates the issue; there are 5 tools that can't be seen (pushed off the right-hand side) but there's no way to tell!

![screen shot 2015-10-23 at 10 18 36](https://cloud.githubusercontent.com/assets/47528/10688885/72b5be6c-796f-11e5-9ac0-d7820e30f112.png)

See also: #580

**Comment by runrevelanor** [comment]
This seems to be a paletteActions widget issue. When the width of the widget changes perhaps the height could change so all the actions can be seen. The Project Browser could handle this change to the size of the footer.

**Comment by jameshale** [comment]
Now here is a case for wrapping the tools to a second line. And perhaps also grouping them by function (in the above image the alignment actions are split.)
