### ISSUE TITLE
Project browser doesn't update when script-only stack is created

### ISSUE THREAD

**Issue by peter-b** [livecode/livecode-ide#583]
Steps to reproduce:
1. Start the IDE
2. Open the project browser
3. In the message box, run `create script only stack`
4. Note that the stack is _not_ listed in the project browser
5. Close the project browser
6. Re-open the project browser
7. Note that the stack is now listed (as "stack id 1001", probably)

I would expect the project browser to update immediately after creating the stack.

**Comment by runrevelanor** [comment]
Reported in the LiveCode QCC

http://quality.runrev.com/show_bug.cgi?id=16283
