### ISSUE TITLE
"Invalid default folder" error on startup on Windows

### ISSUE THREAD

**Issue by peter-b** [livecode/livecode-ide#609]
When running the IDE from the build tree on Windows, I receive the following error in the message box on startup:

```
ERROR: Invalid default folder: C:/Users/Peter/git/livecode/ide/Toolset/propertyInspectorControllers
line: 3473
handler: revIDEPushDefaultFolder
script object: stack "C:/Users/Peter/git/livecode/ide/Toolset/libraries/revidelibrary.8.livecodescript"
```

![screen shot 2015-10-28 at 10 47 42](https://cloud.githubusercontent.com/assets/47528/10786302/60c67110-7d61-11e5-8593-af290c2ef0c4.png)

**Comment by livecodeali** [comment]
Should have been fixed by https://github.com/livecode/livecode-ide/commit/964b593110d7e53104cfc20f795475a589a2f1cd

**Comment by peter-b** [comment]
ide submodule in livecode/livecode was out of date. My bad.
