### ISSUE TITLE
Can't open the message box on Windows 10

### ISSUE THREAD

**Issue by peter-b** [livecode/livecode-ide#692]
Steps to reproduce:
- Install LiveCode 8.0.0-dp-10 on Windows 10
- Run the IDE
- Click the "Message Box" button in the menu bar

Expected results: the message box appears

Actual results: nothing happens

**Comment by livecodeali** [comment]
Deleted the preferences and the message box opened, albeit very low down on the screen (so low that it took me a few goes to see it), so I guess it was one of those two things.
