### ISSUE TITLE
Clicking on cards in the Project Browser fails to navigate to them

### ISSUE THREAD

**Issue by peter-b** [livecode/livecode-ide#693]
LiveCode 8.0.0-dp-10 on Windows 10
- Create a new stack
- Create several cards
- Open the Project Browser
- Click on the cards

Expected behaviour: you can navigate between the cards

Actual behaviour: the current card doesn't change

**Comment by livecodeali** [comment]
Related: #714

**Comment by montegoulding** [comment]
I definitely agree that all objects (including stacks which aren't mentioned here) should behave the same way when clicked on but please, please, please make navigation triggered by something other than selection. Or at least have a preference for what does what.

**Comment by mwieder** [comment]
Yes, please. I'd like to be able to edit an object without inadvertently triggering an e.g. opencard handler or something. The way the current (former?) application browser does this is just fine and I think is the behavior that users expect.
