### ISSUE TITLE
Problems copying cards in Project Browser

### ISSUE THREAD

**Issue by peter-b** [livecode/livecode-ide#694]
LiveCode 8.0.0-dp-10 on Windows 10.
- Create two stacks "StackA" and "StackB"
- Make "StackB" a substack of "StackA"
- Add some cards ("Card1", "Card2", "Card3" to "StackB")
- Select "Card1" in the Project Browser
- Right-click on it in the Project Browser and "Copy"
- Select "StackA" in the Project Browser and "Paste Objects"

"Card1" is successfully copied into "StackA"
- Select "Card2" in the Project Browser
- Right-click on it in the Project Browser and "Copy"
- Select "StackA" in the Project Browser and "Paste Objects"

"Card1" gets successfully copied into "StackA" **again**.

The Project Browser shows "StackA" as containing two cards with the same name _and_ ID.  It doesn't appear to be an updating bug because if you close and reopen the Project Browser then the problem persists.

**Comment by livecodeali** [comment]
I believe this is because the 'selected object' was being used instead of the actual card being clicked on to copy.
If I'm right, then this should have fixed it:
https://github.com/livecode/livecode-ide/pull/734

(indeed it is fixed for me in that branch, so I'll mark that as such)
