### ISSUE TITLE
Indented Code is hard to see/doesn't always work

### ISSUE THREAD

**Issue by runrevelanor** [livecode/livecode-ide#698]
If I make a change to some existing code and then hit tab it is formatted but some of the indenting is lost. The size of the indent is very small and hard to see.

![indent](https://cloud.githubusercontent.com/assets/3931397/11497988/7f81b3a8-9814-11e5-869c-46d4eb895b80.PNG)
hard to see.

**Comment by livecodeali** [comment]
@runrevelanor I _think_ this might have been a DP 10 (i.e. preferences) issue. Have you seen the same in earlier versions?

**Comment by livecodeali** [comment]
This was a DP 10 preferences issue.
