### ISSUE TITLE
No way to dismiss a menu in the Property Inspector

### ISSUE THREAD

**Issue by runrevelanor** [livecode/livecode-ide#699]
If you open a menu in the Property Inspector you have to choose something, there is no way to get it to close once it is open. It also stops you from doing anything else in the IDE.
1. Drag on a Navigation Bar
2. Open the PI
3. Click on the Widget Theme so the menu show but don't choose something
4. Click on your stack again, the menu remains open and focused so you can't do anything until you select an item.

**Comment by livecodeali** [comment]
I think this is an engine bug - is it only on windows?

**Comment by livecodeali** [comment]
Definitely an engine bug.
http://quality.livecode.com/show_bug.cgi?id=16579
