### ISSUE TITLE
Extra 'traversalOn' control in the numeric editor causes bad tabbing experience

### ISSUE THREAD

**Issue by runrevelanor** [livecode/livecode-ide#701]
It would be nice if you could tab through the controls in the PI, particularly if the contents of fields could be automatically selected when a field is tabbed into, allowing you to type directly in, replacing the current value.

**Comment by livecodeali** [comment]
@runrevelanor You should be able to tab through the fields already, are you seeing inability to tab in DP 10? 

Automatically selecting should indeed be reinstated.
