### ISSUE TITLE
Header Widget: Names of Header Actions are not fully changed

### ISSUE THREAD

**Issue by runrevelanor** [livecode/livecode-ide#703]
If you add header actions and set their names the parameter passed with the headerAction message is always the original name, so "Add" or "New Item", not the name set the in Property Inspector.

**Comment by livecodepanos** [comment]
Also reported in BZ:

http://quality.livecode.com/show_bug.cgi?id=16520

**Comment by livecodeali** [comment]
Closing as the corresponding BZ report is awaiting merge.
