### ISSUE TITLE
Image picker for Navigation Bar is too big.

### ISSUE THREAD

**Issue by runrevelanor** [livecode/livecode-ide#712]
The images and image picker are huge, especially on smaller screens. If the images were similar in side to the images in the PI I think it would work better. I also find it quite hard to find the one I want, perhaps showing the name of each image, as they seem to be in alphabetical order, might help? Also maybe a filter so if you know what you are looking for you can find it?

![imagepicker](https://cloud.githubusercontent.com/assets/3931397/11626571/b1f9a400-9cdb-11e5-866f-8cc2482c7ee8.PNG)

**Comment by livecodeali** [comment]
Reabsorbed into bugzilla as http://quality.livecode.com/show_bug.cgi?id=16770 and http://quality.livecode.com/show_bug.cgi?id=16769
