### ISSUE TITLE
Project Browser expanding a group opens the stack with group selected

### ISSUE THREAD

**Issue by montegoulding** [livecode/livecode-ide#714]
I'm not sure if this is a bug or by design. It makes it impossible to use the project browser to navigate to a grouped control and use the contextual menu on it without opening the stack. I found this in selectObjects:

```
## If a card or stack is selected we don't want to go to the card
## The user should be able to highlight or expand a card or stack without going to it
if word 1 of tObjectList is "stack" or word 1 of tObjectList is "card" then
    exit selectObjects
end if
```

I think the same is true of groups but I also think there is something odd to the design if some objects behave differently to others. Wouldn't it be better to only open the object if the user double-clicks or add a go button and to do the same thing for every object type? Perhaps on selection in the PB select the object if it is on a currently open card but otherwise require some other action to open the card.

**Comment by livecodeali** [comment]
@montegoulding I agree, the project browser would be much more useful if it only navigated when instructed to.
