### ISSUE TITLE
IDE stacks shouldn't show extra objects with showInvisibles true

### ISSUE THREAD

**Issue by montegoulding** [livecode/livecode-ide#726]
Choose `View > Show Invisible Objects` and look at revMenubar or the project browser.

I suggest adding a `showInvisibles` stack property that you can set on all IDE stacks and plugins. If false the showInvisibles global would have no effect.

**Comment by mwieder** [comment]
Wouldn't that be more confusing? The menu item then becomes "Show Invisible Objects Unless..."
I usually deal with this problem by layering, i.e., making sure that invisible objects stay hidden by placing them behind visible objects. OTOH, the problem you're describing here is the main reason I almost never use that menu item.

**Comment by montegoulding** [comment]
It would hamper the menu item if people use the stack property on their stacks but I think it's a fairly easy bandaid solution to this issue that has impacted various IDE stacks over the years.

**Comment by runrevmark** [comment]
This would have to be an engine property, as the property which controls visibility of 'all' objects is engine-based. Making 'showInvisibleObjects' a stack property too, which inherits would solve the problem though - as you suggest.

**Comment by montegoulding** [comment]
I was originally thinking of a stack property to override the global property but thinking on it again I think a stack property that causes invisibles to show and change the menu to only set the property of the top non IDE stack.

**Comment by livecodeali** [comment]
Bugzilla report: http://quality.livecode.com/show_bug.cgi?id=16244

I do feel like invisibles should only show in IDE stacks if gRevDevelopment is true, but I guess that would require a message and and a frontscript and so on. 

Unless it was tied into the `_ideoverride` development mode property, which could then be set on all stacks which are considered IDE stacks.

**Comment by runrevmark** [comment]
I do think @montegoulding is correct here - really 'show invisible objects' should be a stack-level property which is toggled by the menu item. I think it is probably quite rare that you would want to show invisibles in all stacks at once, more likely it is a temporary thing you want to set on one stack at a time.

**Comment by livecodeali** [comment]
It should perhaps be moved to a different menu then (the `Object` menu maybe?) as everything else in the view menu is global

**Comment by mwieder** [comment]
I think the only time I use the Show Invisible Objects menu item is when I want to make sure that my stacks look ok when someone tries that. Other than that I don't really have any use for it.

There's already an IDE function (can't recall the name off the top of my head) that determines whether a given stack can be debugged, etc..., i.e., non-system stacks. if we could piggyback off that for determining whether to show the invisible objects then I think that would do what's desired, as it also would respect gRevDevelopment.

**Comment by livecodeali** [comment]
Fixed by this: https://github.com/livecode/livecode-ide/pull/953
