### ISSUE TITLE
Exits on suspend checkbox in iOS standalone settings is labeled background audio

### ISSUE THREAD

**Issue by montegoulding** [livecode/livecode-ide#730]
I know that the reason the checkbox was implemented was to enable background audio but exits on suspend is a much broader feature and should be named appropriately.

**Comment by montegoulding** [comment]
Oh, I see this checkbox also hard wires the uibackgroundmode. Please consider this a feature request then to have an option button for background mode and a separate checkbox for exits on suspend.

**Comment by peter-b** [comment]
This is being tracked in [bug 16829](http://quality.livecode.com/show_bug.cgi?id=16829).
