### ISSUE TITLE
Execution errors while opening script editor

### ISSUE THREAD

**Issue by peter-b** [livecode/livecode-ide#750]
In LiveCode 8.0.0 DP 12 on Mac OS X 10.11, opening the script editor causes script errors.

Steps to reproduce:
1. Open the IDE
2. `put true into gRevDevelopment`
3. Create a new stack
4. Press the "Code" button on the menu bar

Expected results: script editor opens
Actual results: execution errors

![screen shot 2016-01-04 at 13 58 53](https://cloud.githubusercontent.com/assets/47528/12090977/52dbbece-b2eb-11e5-8561-9aa8fa1afce9.png)

**Comment by peter-b** [comment]
See also [bug 16680](http://quality.livecode.com/show_bug.cgi?id=16680)

**Comment by livecodeali** [comment]
Pretty sure this is a dupe of 16641
https://github.com/livecode/livecode-ide/pull/743

**Comment by peter-b** [comment]
Fixed by #743.
