### ISSUE TITLE
Can't search in IDE stacks even with "Show IDE stacks in lists"

### ISSUE THREAD

**Issue by peter-b** [livecode/livecode-ide#776]
The "Find and Replace" dialog doesn't permit searching in IDE stacks even when the 'View→Show IDE Stacks In Lists' option is enabled.

![screen shot 2016-01-12 at 15 31 53](https://cloud.githubusercontent.com/assets/47528/12267821/dcea4426-b941-11e5-944f-6692cb28cd05.png)

**Comment by livecodealice** [comment]
Fixed in 8.1.6
