### ISSUE TITLE
Dictionary content appears behind entry list

### ISSUE THREAD

**Issue by livecodeali** [livecode/livecode-ide#822]
![screen shot 2016-01-28 at 09 22 06](https://cloud.githubusercontent.com/assets/3985854/12640192/a24295b0-c5a0-11e5-995d-3b2ff3f66560.png)

I can't find a report for this, although I think it has been noted several times.

Anyway, I've worked out how to solve it, so I thought I'd add an issue.

**Comment by BerndN** [comment]
it was mentioned in Bug 16642

Ben Rubinstein in comment 32 noted

"A second problem, not related to the width of the window, is that if the article is long, then using the scrollbar scrolls the article group under the index box (content disappears behind the index box, reappears in a narrow slice of window above it).  The scrolling area and scrollbar should be limited to the area available for the article display (which would also stop the jiggling effect when clicking between articles)."

**Comment by livecodeali** [comment]
@BerndN Ah thanks Bernd, yes that must be where I saw it mentioned before!
