### ISSUE TITLE
Guides: Extending LiveCode Guide Comments

### ISSUE THREAD

**Issue by runrevelanor** [livecode/livecode-ide#850]
The composed widget section has handler names formatted as code within the text but the basic widget doesn't, I'm not sure which is correct but just for consistency.

**Extension Builder**

Refers to Tools > Widget Builder, should be Tools > Extension Builder.

Move the 1. number across so its doesn't obscure part of the UI

Section 1 should maybe be "Shows the selected extension" or something similar to be consistent with the other sections
- Typo: the extension you wish _the_ develop
- Typo: authored widgets _are_ in the application package
- All LiveCode authored widgets in the application package at: /contents/extensions/ - this is only on Mac, there is not a contents folder on Windows
- Changing the extension id in the source code will also mean it doesn't conflict with the existing extension. - this doesn't make sense yet as we have not seen any source code. All of this could be moved into the **Note:** section about tweaking an existing widget

**Create your own**
The heading for this section appears inside the previous **Note:**

**Declare Type and Identifier**
The "See Select A Developer ID section could be a link?

**Declare Meta Data**
Can we have more of an explanation of what meta data is for, can I add anything I want or is there a list of allowed meta data types.

**Core Handlers**
Can we mention the () after the declaration as this is difference from LiveCode script and might trip people up.

**Draw a Pink Circle**
Can we explain what the code is actually doing including explaining variable declarations and types as again this differs from LCS. Also can we explain what the color value means?

**Test the Code**
Where is the load icon?

**Properties**
Correct the code to 

`private variable mMargin as Real`

`public handler setMargin(in pMargin as Real) returns nothing`

The setMargin and onCreate handlers are the wrong way round.
Can we explain what a member variable is, and all the parts of the setMargin handler, the parameters and return value, just so users know what they are and why they are there.

I think it would be great if setting the circleMargin property caused a visual effect, maybe onPaint needs updated too?

 typo: :LiveCode builder is _typed_

Typing and variable and case sensitivity links don't work.

**Packaging a Widget**
I think this should have its own section, it is briefly mentioned in **Understanding Error Messages** but is important enough for a little more detail.

**A Simple Composed Widget**
The code for this section doesn't compile.

I think the screenshot at the top is wrong, it should be of the clock/selector widget.

It might be worth explicitly mentioning to create a new folder and source file.

The first code block is missing 'end widget' at the end. 

Can we explain when OnMouseEnter and OnMouseUp happen. I think that it might be clearer to add the variables these handlers use here, or at explain what they are for in more detail.

This section doesn't really have a conclusion, perhaps mention testing, packaging and have a screen shot of the finished widget?

**Comment by livecodeali** [comment]
Transferred relevant info to http://quality.livecode.com/show_bug.cgi?id=19170
