### ISSUE TITLE
Scrolling a Dictionary entry scrolls behind the search results.

### ISSUE THREAD

**Issue by runrevelanor** [livecode/livecode-ide#859]
Select a long Dictionary entry, like libURLLastHTTPHeaders. If you scroll the entry is scrolls up behind the list of results.
![dictionaryscroll](https://cloud.githubusercontent.com/assets/3931397/12823599/cdf99a0e-cb64-11e5-8a3d-283c20c956c0.png)

**Comment by livecodeali** [comment]
This is fixed in the develop branch.
https://github.com/livecode/livecode-ide/pull/824
