### ISSUE TITLE
A  button with an icon shows parts of the icon outside the selection area

### ISSUE THREAD

**Issue by runrevelanor** [livecode/livecode-ide#861]
Set an icon on a button and select the button. Part of the icon shows outside the size of the button, this only happens when the button is selected.

![2016-02-04 15_31_34-untitled 1 1 _](https://cloud.githubusercontent.com/assets/3931397/12823722/7d3bd18a-cb65-11e5-981d-9369631d3761.png)

**Comment by livecodeali** [comment]
Fixed: https://github.com/livecode/livecode/pull/3734
