### ISSUE TITLE
The Message Box doesn't do calculations without using put

### ISSUE THREAD

**Issue by runrevelanor** [livecode/livecode-ide#879]
Doing

450/4

in the Message Box gives the error

Script compile error:
Error description: Handler: bad command

put 450/4

works as expected

**Comment by peter-b** [comment]
@runrevelanor Is this the same problem as [bug 16863](http://quality.livecode.com/show_bug.cgi?id=16863)?

**Comment by livecodepanos** [comment]
@peter-b Yes it is the same.

Closing this issue then. (See [bug 16863](http://quality.livecode.com/show_bug.cgi?id=16863) for updates)
