### ISSUE TITLE
Advanced pane inconsistency

### ISSUE THREAD

**Issue by montegoulding** [livecode/livecode-ide#894]
There are two issues I noticed about the advanced pane:
- There is no advanced pane for cards and stacks. Is there somewhere else the behavior controls are moved to?
- The `Layer Mode` and `Behavior` controls are in different orders on widgets v legacy objects.
  ![screen shot 2016-02-12 at 4 27 46 pm](https://cloud.githubusercontent.com/assets/351144/12999673/bf603fa6-d1a5-11e5-91bd-de379c20931e.png)
  ![screen shot 2016-02-12 at 4 27 59 pm](https://cloud.githubusercontent.com/assets/351144/12999672/bf5da5ca-d1a5-11e5-9215-c235499779c2.png)

**Comment by livecodeali** [comment]
@montegoulding The first of these is fixed in develop - apparently there wasn't a behavior field in the PI for cards and stacks at all before.

**Comment by montegoulding** [comment]
Oh, ok I thought I had pulled the latest

**Comment by peter-b** [comment]
Sometimes the livecode/livecode repository's "ide" submodule pointer gets out of sync with the livecode/livecode-ide's latest contents. Sorry...

**Comment by montegoulding** [comment]
Ah, that'd be it. So what do you guys do? Check out develop on the submodules and then avoid committing the submodules references in the parent repo when working on stuff there?

**Comment by peter-b** [comment]
Yes, that's right.  It saves merge conflicts.

**Comment by montegoulding** [comment]
Ok, I'll try and remember to do that.
