### ISSUE TITLE
Custom property element values aren't retained if you select another key

### ISSUE THREAD

**Issue by montegoulding** [livecode/livecode-ide#895]
As you can see here the element values aren't retained because I am clicking on the widget. It appears to only set the value if you select the key field or focus out on the stack. Perhaps it would be good to use textChanged and show the changes live on the selected node?

![customproperties](https://cloud.githubusercontent.com/assets/351144/12999918/83c13fce-d1a8-11e5-8745-4191f73cc76c.gif)

**Comment by livecodepanos** [comment]
This is now fixed, tested with LC 8.1.6 rc3
