### ISSUE TITLE
PI: Behavior selector should is a bit odd

### ISSUE THREAD

**Issue by montegoulding** [livecode/livecode-ide#916]
The behavior selector should popup on mouseDown rather than mouseUp. I'd also be keen to be able to drag a line out to the button, stack or project browser similar to Interface Builder but I'm guessing that would be rather interesting to implement in a multi-window environment. It's worth noting that the reason I thought of the latter is because of the mouseDown highlight and no popup made me thing it was how it worked and it wasn't until I finally mouseUp'ed on on the widget that I realised there's a popup.

**Comment by runrevmark** [comment]
The drag to connect thing could be done in a similar vein to how the tools palette does drag-drop.

**Comment by montegoulding** [comment]
Yes.. although dragging out a line would be neat just highlighting buttons and stacks as you drag around would work

**Comment by livecodeali** [comment]
I've made a new issue for the dragging enhancement.
