### ISSUE TITLE
Dictionary: Sort order of library list is variable

### ISSUE THREAD

**Issue by montegoulding** [livecode/livecode-ide#923]
The order order of the library list is variable each time it is rebuilt a different order is seen with LCS And LCB always at the top. It might be worth having the two main libraries and then submenus in reasonably well thought out categories considering the number of widgets and libraries that might be represented there eventually. Either way some sort of reliable order would be good.

**Comment by bwmilby** [comment]
PR 1683 addressed the sorting part of this.

**Comment by livecodeali** [comment]
I'm going to say this is closed - the libs are all now either in the LCS or LCB APIs, and the subcategory part is doable using the associations filter
