### ISSUE TITLE
Message box: the icons on the bottom left are mysterious

### ISSUE THREAD

**Issue by livecodefraser** [livecode/livecode-ide#958]
The "target" and "padlock" icons don't have tooltips and their purpose is non-obvious.

**Comment by runrevelanor** [comment]
These existed in dp-14, I think this issue is the same as

http://quality.livecode.com/show_bug.cgi?id=17005

So I'll close it here.

**Comment by mwieder** [comment]
? 17005 is about tooltips for bundled widgets on the tools palette.

**Comment by runrevelanor** [comment]
Yes, I thought it was a more general issue about tooltips not showing on widgets but that issue this not fix this one so I am re-opening this issue.

The tooltips were present in dp14 but not in dp15 onwards.

**Comment by livecodeali** [comment]
This issue is the same as http://quality.livecode.com/show_bug.cgi?id=17273
