### ISSUE TITLE
Tutorial issues

### ISSUE THREAD

**Issue by livecodefraser** [livecode/livecode-ide#983]
Some tutorial issues I've noticed:
- [x] Instruction to 'Check the "Don't Wrap"' box for the advice field should be 'Uncheck'
- [x] Graph widget no longer has 'Graph Colors' property; now called 'Line Colors'
- [x] When using the "copy code to script editor" button, it would be nice to insert some comments on the code, too (perhaps repeating the explanations of the code the tutorial gives)
- [x] The icons underneath the progress bar on the tutorial pane of the menubar both appear as stars
- [x] I didn't get an explanation for the card script that sets cBMI
- [x] nor the script for the calculate BMI button
- [x] nor the script for the header bar
- [x] "We are going to use the custom property set on the stack in order to highlight where on the chart the last calculated BMI is located." message doesn't give an instruction; the next step is only apparent because only one item in the object menu is non-disabled (seems a little confusing when every other step gives explicit instructions and, for new users, editing the script isn't obviously how you would do this).
- [x] Might be nice if the first time that adding script comes up to say "normally, you'd write this yourself but, this time, here's some I made earlier so we can explain how it works"
- [x] Explanation of the project browser could be a bit opaque to new users. What's "unfold"ing a "tree view"? (Not that I have any better ideas...)

The engine also crashed after adding a new navbar item for the browser widget card, but I think that's probably a CEF-related issue ;)

**Comment by livecodeali** [comment]
First checkbox: https://github.com/livecode/livecode-ide/pull/1002

**Comment by livecodeali** [comment]
More issues: https://github.com/livecode/livecode-ide/pull/1013
