### ISSUE TITLE
PI minor issue grab-basket

### ISSUE THREAD

**Issue by livecodefraser** [livecode/livecode-ide#984]
A selection of minor PI issues that I came across while going through the tutorial:
- [x] When editing the name of items in the navbar widget, it'd be nice if clicking on the name selected the text in the field so that users can just start typing rather than having to manually delete the contents
- [x] Name editing fields in the navbar item editor are too small for the default text font/size on Ubuntu
- [x] Item names in the navbar item editor cut off the end of the text by a pixel or two
- [x] Buttons can also have multi-line labels and the PI doesn't provide an obvious way to enter them
- [ ] Related to the above, using Return/Ctrl+Return for non-field/field labels/content is confusingly inconsistent, especially as "label" controls are really fields.
- [ ] Icon picker scrollbar is barely visible and too small a click target

**Comment by livecodeali** [comment]
Icon picker scrollbar: http://quality.livecode.com/show_bug.cgi?id=17136
I'm not sure what to do about the second-to-last point. Do we remove ability to accept single-line properties using `<Return>`? Do we change the tutorial to always use `<Ctrl>+<Return>`? This is perhaps more than a minor issue.
