### ISSUE TITLE
revSaving field overflow

### ISSUE THREAD

**Issue by livecodeali** [livecode/livecode-ide#986]
![screen shot 2016-03-11 at 12 02 33](https://cloud.githubusercontent.com/assets/3985854/13701588/deec16ec-e780-11e5-978e-a0d0c24175c4.png)

**Comment by runrevelanor** [comment]
I can't recreate this, it looks wrong if you just open the stack revSaving but all the sizes are set by a setProp when the stack is to be shown and it looks ok on all the stacks I tested on. If you have a recipe I'll look into it again. Thanks.

**Comment by livecodeali** [comment]
Yep, it seems to be fixed!
