### ISSUE TITLE
Project Browser: preference updates

### ISSUE THREAD

**Issue by runrevelanor** [livecode/livecode-ide#988]
I think the Project Browser preferences (in the Preferences stack) need updated.
- [x] There aren't any thumbnails in the new Project Browser
- [x] Setting the Text size does resize the text but the lines don't get taller
- [x] The sort order option is only in the Preferences stack, not in the header options of the Project Browser.

**Comment by livecodeali** [comment]
PR: https://github.com/livecode/livecode-ide/pull/1095

**Comment by livecodeali** [comment]
Closed erroneously - PR fixes pt 3.

**Comment by livecodeali** [comment]
Part 2 will be handled as part of https://github.com/livecode/livecode-ide/issues/1096
