### ISSUE TITLE
Standardise the behaviour of the Tools Palette across widgets and classic controls

### ISSUE THREAD

**Issue by runrevelanor** [livecode/livecode-ide#995]
In the Tools Palette classic controls have a hover state and tooltip but widgets don't have either. It would be nice if this was standardised, I think tooltips in particular would be useful, for example to show that the globe icon is a browser widget.

**Comment by livecodeali** [comment]
They have tooltips being set on them which were working in previous versions, so that part as least is some sort of bug.

**Comment by runrevelanor** [comment]
This is also in bugzilla

http://quality.livecode.com/show_bug.cgi?id=17005

So I'll close it here.
